---
name: Tie-DiskUsage
version: 0.20_01
author:
  - 'Steven Schubiger <schubiger@cpan.org>'
abstract: Tie disk usage to a hash
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  File::Spec: 0
  File::Temp: 0
  Test::More: 0
requires:
  Carp: 0
  Cwd: 0
  File::Which: 0
  Symbol: 0
  Tie::Hash: 0
recommends:
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
configure_requires:
  Module::Build: 0.34
provides:
  Tie::DiskUsage:
    file: lib/Tie/DiskUsage.pm
    version: 0.20_01
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
