---
name: Tie-DiskUsage
version: 0.18
author:
  - 'Steven Schubiger <schubiger@cpan.org>'
abstract: Tie disk-usage to a hash
license: perl
requires:
  Carp: 0
  File::Basename: 0
  File::Which: 0
  Symbol: 0
  Tie::Hash: 0
build_requires:
  Test::More: 0
recommends:
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  Tie::DiskUsage:
    file: lib/Tie/DiskUsage.pm
    version: 0.18
resources:
  license: http://dev.perl.org/licenses/
