---
name: Safe-Caller
version: 0.03
author:
  - 'Steven Schubiger <schubiger@cpan.org>'
abstract: A nicer interface to caller() with code execution restriction
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
recommends:
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
provides:
  Safe::Caller:
    file: lib/Safe/Caller.pm
    version: 0.03
generated_by: Module::Build version 0.2801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
