---
name: Text-Wrap-Smart-XS
version: 0.05
author:
  - 'Steven Schubiger <schubiger@cpan.org>'
abstract: Wrap text fast into chunks of (mostly) equal length
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
build_requires:
  ExtUtils::CBuilder: 0
  Test::More: 0
recommends:
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
provides:
  Text::Wrap::Smart::XS:
    file: lib/Text/Wrap/Smart/XS.pm
    version: 0.05
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
