---
name: Acme-Text-Rhombus
version: 0.18_01
author:
  - 'Steven Schubiger <schubiger@cpan.org>'
abstract: Draw a rhombus with letters
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
requires:
  Exporter: 0
recommends:
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
configure_requires:
  Module::Build: 0.34
provides:
  Acme::Text::Rhombus:
    file: lib/Acme/Text/Rhombus.pm
    version: 0.18_01
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
