---
name: LaTeX-Pod
version: 0.18_02
author:
  - 'Steven Schubiger <schubiger@cpan.org>'
abstract: Transform LaTeX source files to POD (Plain old documentation)
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Getopt::Long: 0
  LaTeX::TOM: 0
  Params::Validate: 0
  boolean: 0
build_requires:
  File::Spec: 0
  FindBin: 0
  Test::More: 0
recommends:
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
provides:
  LaTeX::Pod:
    file: lib/LaTeX/Pod.pm
    version: 0.18_02
generated_by: Module::Build version 0.3201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
