---
name: BSD-Getfsent
version: 0.14
author:
  - 'Steven Schubiger <schubiger@cpan.org>'
abstract: Get file system descriptor file entry
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Exporter: 0
  IO::File: 0
build_requires:
  Test::More: 0
recommends:
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
provides:
  BSD::Getfsent:
    file: lib/BSD/Getfsent.pm
    version: 0.14
generated_by: Module::Build version 0.2709
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
