---
name: Hook-Output-File
version: 0.02
author:
  - 'Steven Schubiger <schubiger@cpan.org>'
abstract: Redirect STDOUT/STDERR to a file
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  File::Spec: 0
  Tie::Handle: 0
build_requires:
  Test::More: 0
recommends:
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
provides:
  Hook::Output::File:
    file: lib/Hook/Output/File.pm
    version: 0.02
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
