---
name: DateTime-Format-Natural
version: 0.75_05
author:
  - 'Steven Schubiger <schubiger@cpan.org>'
abstract: Create machine readable date/time with natural parsing logic
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  DateTime: 0
  List::MoreUtils: 0
  Params::Validate: 0
  Term::ReadLine: 0
  boolean: 0
build_requires:
  Test::MockTime: 0
  Test::More: 0
recommends:
  Date::Calc: 0
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
provides:
  DateTime::Format::Natural:
    file: lib/DateTime/Format/Natural.pm
    version: 0.75_05
  DateTime::Format::Natural::Base:
    file: lib/DateTime/Format/Natural/Base.pm
    version: 1.24
  DateTime::Format::Natural::Compat:
    file: lib/DateTime/Format/Natural/Compat.pm
    version: 0.03
  DateTime::Format::Natural::Helpers:
    file: lib/DateTime/Format/Natural/Helpers.pm
    version: 0.01
  DateTime::Format::Natural::Lang::Base:
    file: lib/DateTime/Format/Natural/Lang/Base.pm
    version: 1.00
  DateTime::Format::Natural::Lang::EN:
    file: lib/DateTime/Format/Natural/Lang/EN.pm
    version: 1.20
generated_by: Module::Build version 0.3201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
