---
name: DateTime-Format-Natural
version: 0.23_01
author:
  - 'Steven Schubiger <schubiger@cpan.org>'
abstract: Create machine readable date/time with natural parsing logic
license: perl
requires:
  Date::Calc: 0
  DateTime: 0
build_requires:
  Test::More: 0
recommends:
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  DateTime::Format::Natural:
    file: lib/DateTime/Format/Natural.pm
    version: 0.23_01
  DateTime::Format::Natural::Base:
    file: lib/DateTime/Format/Natural/Base.pm
    version: 0.6
  DateTime::Format::Natural::Lang::Base:
    file: lib/DateTime/Format/Natural/Lang/Base.pm
    version: 0.2
  DateTime::Format::Natural::Lang::DE:
    file: lib/DateTime/Format/Natural/Lang/DE.pm
    version: 0.5
  DateTime::Format::Natural::Lang::EN:
    file: lib/DateTime/Format/Natural/Lang/EN.pm
    version: 0.6
resources:
  license: http://dev.perl.org/licenses/
