---
name: DateTime-Format-Natural
version: 0.68
author:
  - 'Steven Schubiger <schubiger@cpan.org>'
abstract: Create machine readable date/time with natural parsing logic
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Date::Calc: 0
  DateTime: 0
  List::MoreUtils: 0
  Term::ReadLine: 0
build_requires:
  Test::MockTime: 0
  Test::More: 0
recommends:
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
provides:
  DateTime::Format::Natural:
    file: lib/DateTime/Format/Natural.pm
    version: 0.68
  DateTime::Format::Natural::Base:
    file: lib/DateTime/Format/Natural/Base.pm
    version: 1.10
  DateTime::Format::Natural::Lang::Base:
    file: lib/DateTime/Format/Natural/Lang/Base.pm
    version: 0.8
  DateTime::Format::Natural::Lang::EN:
    file: lib/DateTime/Format/Natural/Lang/EN.pm
    version: 1.11
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
